### ISSUE TITLE
Ui update of Home.js

### ISSUE THREAD

**Issue by vishalverma9572** [vishalverma9572/QuizMaster#1]
update UI of landing page matching with other pages

**Comment by khushiiagrawal** [comment]
hey! i want to work on the landing page

**Comment by Aiu26** [comment]
@vishalverma9572 can you assign this to me under hacktoberfest

**Comment by vishalverma9572** [comment]
@khushiiagrawal assigned

**Comment by vishalverma9572** [comment]
@Aiu26  If you're interested, you are welcome to work on this issue as well as any other ones that might catch your attention. Your help would be greatly appreciated!

**Comment by mahenoorsalat** [comment]
hello @vishalverma9572 can you please assign me this pr .. looking forward to your response .. Thank you:)

**Comment by khushiiagrawal** [comment]
hey, i have one question 
as you have mentioned this "update UI of landing page matching with other pages" but the right now all the pages look quiet similar to each other. So can I add different colour contrast and make it more attractive ?

**Comment by Aiu26** [comment]
@vishalverma9572 I would like to work on issue #3, under hacktoberfest

**Comment by shreyajaiswal17** [comment]
@vishalverma9572 I would like to work for this.

**Comment by vishalverma9572** [comment]
@khushiiagrawal give it a try! If it looks good, I'll consider it.
