### ISSUE TITLE
Let users take quiz according to their selected category

### ISSUE THREAD

**Issue by Aneeshaik** [vishalverma9572/QuizMaster#10]
![Screenshot 2024-10-02 125511](https://github.com/user-attachments/assets/350285b1-f34f-4ae6-a438-246a4058c7d3)

Enhance the Take Test section by adding some categories and let users to select the category. Then, according to their category render the Quiz. I can do it from my end. Please assign it to me under hactoberfest2024. 
Thank You!

**Comment by vishalverma9572** [comment]
@Aneeshaik, we don't have a category in our test, but you can work on it. I'm assigning it to you. Please make sure the UI aligns with the other pages.

**Comment by Aneeshaik** [comment]
Okay! Thank you. If user want to take quiz of specific language like javascript, reactjs etc like or if he wants to take a specific quiz regarding any topics. I would like to categorise like this.

**Comment by Aneeshaik** [comment]
@vishalverma9572  okay! Could you please tell how to take test?

**Comment by vishalverma9572** [comment]
@Aneeshaik, To take the test, you need to enter the quiz ID in the provided input and click on 'Search': vishalverma_acadwzt0e6. this is a sample test id.

**Comment by Aneeshaik** [comment]
> vishalverma_acadwzt0e6

Now, I totally understand why you said we don't have a category in this quiz app. This app is to create a quiz and give that specific Quiz I'd to someone to write the quiz, right? What I meant in my issue is Let's make one practice tests section, we will provide some practice quizzes there regarding some topics where users can check their knowledge in whatever language or topics they want to check. Is it ok for you?

**Comment by Aneeshaik** [comment]
@vishalverma9572 Can I proceed?

**Comment by vishalverma9572** [comment]
@Aneeshaik yeah sure!

**Comment by vishalverma9572** [comment]
@Aneeshaik  are you workin on this?

**Comment by Aneeshaik** [comment]
@vishalverma9572 actually, I got task from a company, was busy in that and i completed that task. Now, I'll work on this.

**Comment by Aneeshaik** [comment]
Hey @vishalverma9572 ! Please close this issue. As I got lot of work, I am unable to work on this. I hope you understand the situation. Thank you!
