### ISSUE TITLE
[logout] No logout feature in the website 

### ISSUE THREAD

**Issue by agnijeetsharma** [vishalverma9572/QuizMaster#100]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

There is no logout feature in the website .I can integrate this feature .
@vis Kindly assign me this issue under hacktoberfest 2024

### Proposed Solution

I can integrate a logout feature in the website . After logout user will navigate to the homepage of the website and their moves will restricted 

### Screenshots

![Screenshot 2024-10-11 152105](https://github.com/user-attachments/assets/1a17f3a0-01fc-4209-bce4-b2b76919b8f2)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I will create a button or toggle sign in to logout . Just clear all the details of the user form the website and navigate to the  homepage .This is backend feature so kindly assign me this issue under hacktoberfest-2024

**Comment by vishalverma9572** [comment]
@agnijeetsharma , There is a button in sidebar for logout. check it carefully!

**Comment by vishalverma9572** [comment]
@agnijeetsharma , please find another issues or features to work upon! Thank You
