### ISSUE TITLE
[BUG] <Scroll down bug , attached image of the bug>

### ISSUE THREAD

**Issue by agnijeetsharma** [vishalverma9572/QuizMaster#101]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

There is a bug in the website, whenever user will scroll down home page ,he will encounter a bug.
I have attached screenshot of the bug
@vishalverma9572 kindly assign me this issue under hacktoberfest-2024

### Steps to Reproduce

Include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Screenshots

![Screenshot 2024-10-11 153143](https://github.com/user-attachments/assets/5cc3d9d0-c24b-4121-9b5e-7e0d91202d56)
![Screenshot 2024-10-11 153512](https://github.com/user-attachments/assets/63434d9d-5274-461a-8adf-88033d9108fc)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

The background color is not properly worked here .i have to fix some CSS add some basic property of scrolling.
@vishalverma9572 Kindly assign me this issue under hacktoberfest-2024
I will fix this bug ASAP.

**Comment by vishalverma9572** [comment]
@agnijeetsharma , You can update the UI of complete Home page!

**Comment by vishalverma9572** [comment]
@agnijeetsharma , make sure you follow our code structure and UI theme!

**Comment by agnijeetsharma** [comment]
@vishalverma9572 Kindly label the issue hacktoberfest

**Comment by agnijeetsharma** [comment]
@vishalverma9572  Done PR#102
