### ISSUE TITLE
[BUG] FORGOT PASSWORD MAIL NOT WORKING

### ISSUE THREAD

**Issue by ash956901** [vishalverma9572/QuizMaster#103]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

Upon clicking on forgot password, and sending the mail from the website, the site doesnt send email to the designated mailbox, for password recovery.

### Steps to Reproduce

- Go to Login Page
- Click On Forgot Password
- Enter The Email
- Get the successful message sent message
- open your mailbox
- no email is there

### Screenshots

<img width="1440" alt="Screenshot 2024-10-11 at 6 04 34 PM" src="https://github.com/user-attachments/assets/5f4073e3-9dce-4a2f-b308-d1e26bd4f913">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I would go through the whole mail sender flow, and check if there are any vulnerabilities in the secrets , if not then i will debug at each step to check where the mail process has gone wrong , if the whole flow is wrong , i will try implementing another method of sending the mail.

**Comment by ash956901** [comment]
Pls sir I would like to work on this

**Comment by vishalverma9572** [comment]
@ash956901  assigned!

**Comment by ash956901** [comment]
thanks sir will get it ready asap

**Comment by ash956901** [comment]
@vishalverma9572 i have put the pr , please merge it as i have fixed the reset password flow

**Comment by ash956901** [comment]
@vishalverma9572 could u please merge this pr before midnight? it would be of huge help...
