### ISSUE TITLE
[BUG] sidebar link is not clickable properly

### ISSUE THREAD

**Issue by Shariar-Hasan** [vishalverma9572/QuizMaster#107]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

for example:
click and routing working on the blue line 
but not in the red line
![image](https://github.com/user-attachments/assets/b1e5022f-3259-454e-98d0-cda25d36a166)

### Steps to Reproduce

Include any relevant details like:

- dashboard page issue
- i am trying to fix the issue
- sidebar link is not clickable properly

### Screenshots

![image](https://github.com/user-attachments/assets/a8bf891a-8dd1-4fd7-bba7-276458eb9513)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

i will try to wrap up the whole item with link component

**Comment by vishalverma9572** [comment]
@Shariar-Hasan, assigned!

**Comment by Shariar-Hasan** [comment]
made a PR #125
