### ISSUE TITLE
[FEATURE] Add dark mode.

### ISSUE THREAD

**Issue by taneeshaa15** [vishalverma9572/QuizMaster#112]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

no

### Proposed Solution

no

### Do you want to work on this issue?

Yes

**Comment by taneeshaa15** [comment]
@vishalverma9572 Please assign me this issue under hacktoberfest.

**Comment by vishalverma9572** [comment]
@taneeshaa15 , Since we are currently focusing on just one theme and not supporting a dark theme, you can shift your efforts toward resolving other issues or contributing in different areas. Thanks for your understanding and cooperation!
