### ISSUE TITLE
[FEATURE] No close button on sign up and sign in prompt 

### ISSUE THREAD

**Issue by ParvamShah1** [vishalverma9572/QuizMaster#114]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The feature request suggests adding a close button to the sign-up and sign-in prompts for improved user experience. This will give users the flexibility to easily exit or cancel the process if they are not ready to sign up or log in. By incorporating a clearly visible close button, the interface becomes more intuitive and user-friendly, reducing frustration and ensuring users can quickly back out of the process without confusion. This feature enhances the overall navigation flow and allows users to have more control over their interaction with the sign-up/sign-in modal.

### Proposed Solution

To solve this, I'll add a close button to the sign-up and sign-in modals, making it easier for users to exit the process. This will involve updating the modal design to include a visible "X" button, ensuring it’s intuitive and blends with the site’s theme. The button will close the modal without refreshing the page or disrupting the session. I'll test the feature to ensure smooth functionality across devices, improving the overall user experience.

### Screenshots

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/884ea072-c22d-4d85-9513-58f14fad5857">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

To implement the close button for the sign-up and sign-in modals, I will follow these technical steps:

Update the Modal Component:

In the modal's HTML structure, I'll add a close button (an <button> or an <i> element for an "X" icon) at the top-right corner. This will be included in the JSX if using React.
Styling:

I'll apply CSS styles to the close button to ensure it is visually appealing and consistent with the rest of the modal. This includes positioning it correctly, adjusting size, and applying hover effects for better interactivity.

Event Handling:

I'll attach an event listener to the close button that triggers a function to hide the modal. This will typically involve setting a state variable (e.g., isOpen) to false in React, or manipulating the DOM directly with JavaScript or jQuery.
Accessibility:

To ensure accessibility, I’ll add aria-label attributes and ensure the button is focusable, allowing keyboard navigation and screen reader support.

Testing:

After implementing the feature, I'll conduct thorough testing across different devices and browsers to ensure the close button functions correctly and does not interfere with form submissions or user sessions.

By following these steps, the close button will enhance user interaction with the sign-up and sign-in modals effectively.

**Comment by vishalverma9572** [comment]
@ParvamShah1 , assigned!
