### ISSUE TITLE
UI Improvements in Profile Page

### ISSUE THREAD

**Issue by marvelxcodes** [vishalverma9572/QuizMaster#13]
I can improve the ui of the Profile page and I'll add change password button to profile page
![image](https://github.com/user-attachments/assets/de2235eb-edec-46c4-9135-88569813fe04)

**Comment by Kheria1509** [comment]
hey @vishalverma9572 i would like to contribute in UI design for profile page.
can you allow me to contribute ?

**Comment by marvelxcodes** [comment]
@vishalverma9572 yeah sure

**Comment by vishalverma9572** [comment]
@marvelxcodes. any updates?
