### ISSUE TITLE
style the homepage and about page

### ISSUE THREAD

**Issue by Vardhan-Harsh07** [vishalverma9572/QuizMaster#130]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

![image](https://github.com/user-attachments/assets/d8d11cd6-a1af-4dd1-8490-26afd98e239e)
![image](https://github.com/user-attachments/assets/419552a0-d67c-4aa2-8940-64ed74b7b266)
both of them are looking very outdated also the navbar in about page is looking way too odd also if we click the  logo in navbar it should redirect to the homepage which it is not foing 

### Proposed Solution

in big 2024 atleast the frontend should be eyecatchy i can improve it also in navbar of about page i can put id into logo so that it can reddirect to homepage u can assign the work to me i ll make sure u will like it :)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

To implement the proposed changes, I would start by refactoring the CSS using a modern framework like Tailwind CSS or Bootstrap to create a more visually appealing and responsive design. I would also update the HTML structure of the navbar, ensuring that the logo is wrapped in an <a> tag with a proper href="/" link to redirect to the homepage. If needed, I could add a small JavaScript snippet to handle smooth navigation. For the alignment issue on the "About" page, I would apply consistent CSS styles across all pages, ensuring the navbar elements are properly aligned with flexbox for a clean and balanced look. This approach will ensure the frontend feels fresh, functional, and user-friendly across all devices.

**Comment by vishalverma9572** [comment]
@Vardhan-Harsh07 , assigned!

**Comment by vishalverma9572** [comment]
check PR #152
