### ISSUE TITLE
[BUG] Toast for successfull api calls instead of alerts

### ISSUE THREAD

**Issue by Ehm-Ehs** [vishalverma9572/QuizMaster#133]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

<img width="1440" alt="Screenshot 2024-10-15 at 11 00 42" src="https://github.com/user-attachments/assets/2b209f66-25c1-4a47-beb1-763465329b4b">
 on success of api calls alerts shows up these alerts can be changed to toasts from react-toastify or any other toast library

### Steps to Reproduce

Include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

i would install react toastify and implement a custom toast container then change all alerts to toast

**Comment by vishalverma9572** [comment]
@Ehm-Ehs, Assigned! Please follow our code structure and UI theme as closely as possible.
