### ISSUE TITLE
[BUG] Improve UI of existing user guide page 

### ISSUE THREAD

**Issue by gt951436** [vishalverma9572/QuizMaster#135]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The existing UI of the user guide page does not provide user a good reading experience and does not leave a good impression on user, so i will improve the UI and the functionality.

### Steps to Reproduce

- On user guide page.
- The Buttons present are taking up unnecessary space .
- The UI of the page is not very impressive leading to bad user experience.

### Screenshots

![Screenshot 2024-10-15 214814](https://github.com/user-attachments/assets/d6c2b239-0e99-4de2-9b63-e18bf49d9c73)
![Screenshot 2024-10-15 214829](https://github.com/user-attachments/assets/f190c195-8d48-468f-b9d7-1a9990b951e5)

### Do you want to work on this issue?

Yes

**Comment by gt951436** [comment]
@vishalverma9572 please assign this issue to me and add the hactober fest label to it.

**Comment by vishalverma9572** [comment]
@gt951436 , assigned!

**Comment by gt951436** [comment]
@vishalverma9572 please review this PR.

**Comment by saradha04** [comment]
ill commit this issue
