### ISSUE TITLE
There's a bug in the My Results section and some typos. Please correct this issue and make sure to address all similar mistakes

### ISSUE THREAD

**Issue by umar-9540** [vishalverma9572/QuizMaster#15]
When we click on My Results section button it shows "My Tests " as header instead of "My Results". 

Could you please assign this to me??
![image_2024-10-02_155855608](https://github.com/user-attachments/assets/81f9c5f0-c29c-4ee4-800f-a93f8a0c1843)

**Comment by vishalverma9572** [comment]
@umar-9540 There is a typo, I have corrected that thankyou so much . If you find any similar bugs please resolve those bugs and create a PR

**Comment by umar-9540** [comment]
Thank you! I'm looking forward to contributing.
