### ISSUE TITLE
Heading in Create Test and Take Test sections

### ISSUE THREAD

**Issue by umar-9540** [vishalverma9572/QuizMaster#17]
There are heading in other three sections but in "Create Test" and "Take Test" sections there is no heading. I would like to add those headings if you could assign this task to me.

![image_2024-10-02_161147224](https://github.com/user-attachments/assets/10d6376c-f151-46c1-afb5-1d6c81a2d7fc)
![image_2024-10-02_161227901](https://github.com/user-attachments/assets/5f4c0db8-b3b6-453b-bb37-ff1220069408)

**Comment by vishalverma9572** [comment]
@umar-9540 Go for It!
