### ISSUE TITLE
create a good loader page for dashboard 

### ISSUE THREAD

**Issue by vishalverma9572** [vishalverma9572/QuizMaster#2]

**Comment by dhyey0011** [comment]
I would like to work on it. Please assign it to me
.

**Comment by aachintya** [comment]
i can work for a solution. Can you assign it to me ?

**Comment by vishalverma9572** [comment]
@dhyey0011 assigned!

**Comment by vishalverma9572** [comment]
@aachintya , You can work on this as well !
