### ISSUE TITLE
Refactor All Try Catch block to use a sinlge global error handler, ChatBot required, Email verification add at signup

### ISSUE THREAD

**Issue by Shub95-arch** [vishalverma9572/QuizMaster#23]
# Feature Request: Global Error Handler, Chatbot with Socket.IO, and Email Verification

## Overview

This issue outlines the need to refactor the project to include the following features:

1. **Global Error Handler**
   - Refactor all try/catch blocks to utilize a single global error handler.

2. **Chatbot Implementation**
   - Implement a chatbot using Socket.IO for real-time communication.

3. **Email Verification at Signup**
   - Add email verification functionality during the user signup process.

### 1. Global Error Handler
- Create a centralized error handling middleware to manage errors across the application.
- Remove individual try/catch blocks in routes and replace them with calls to the global error handler.

### 2. Chatbot with Socket.IO
- Integrate Socket.IO to enable a real-time chatbot feature.
- Ensure that users can send and receive messages through the chatbot interface.

### 3. Email Verification
- Implement email verification during the signup process.
- Send a verification email to users with a unique link upon registration.
- Create a verification endpoint to handle user verification upon clicking the link.

## Additional Notes
- Ensure that proper testing is conducted for each feature after implementation.
- Update the documentation to reflect any changes made during this process.

**Comment by vishalverma9572** [comment]
@Shub95-arch , thanks for creating this issue. you can start working on this issue Remember, this is a complex task, so start small and create a PR with a solid, small implementation. This will make management easier.

**Comment by vishalverma9572** [comment]
This issue may require other experienced contributors as well, so others are welcome to join

**Comment by Shub95-arch** [comment]
> @Shub95-arch , thanks for creating this issue. you can start working on this issue Remember, this is a complex task, so start small and create a PR with a solid, small implementation. This will make management easier.

Thanks for your consideration on this issue , although i have already made the backend routes for the chatbot and email verification and all the try catch blocks are refactored. Please check the pull request #25 and if it helped contribute to this repo , do mark it has hacktoberfest-accepted. 

Thanks

**Comment by Shub95-arch** [comment]
> This issue may require other experienced contributors as well, so others are welcome to join

Thank you for telling me about some security measures, i have removed personal keys and the environment is safe now, 
I've made another pull request #34
