### ISSUE TITLE
adding a page to require login to view profile

### ISSUE THREAD

**Issue by ayush-848** [vishalverma9572/QuizMaster#24]
![image](https://github.com/user-attachments/assets/f4d6098f-7c88-4ea0-b09a-197effb21de5)

If i directly go to the profile then there will be a page showing Please login to view this page

**Comment by ayush-848** [comment]
PS:- I will also try to hide logout button if user is not logged in

**Comment by vishalverma9572** [comment]
@ayush-848, currently, we are experiencing an email-related issue when users forget their passwords. Therefore, I kindly suggest holding off on this task for now, as it could lead to a poor user experience with limited resources for our users. Thank you for your understanding!
