### ISSUE TITLE
clear local Storage token if authentication is failed and redirect to '/login' for all secure routes

### ISSUE THREAD

**Issue by vishalverma9572** [vishalverma9572/QuizMaster#27]

**Comment by TusharGupta-Developer** [comment]
hey! i want to work on this issue
@vishalverma9572 can you please assign this to me under hacktoberfeast

**Comment by vishalverma9572** [comment]
@TusharGupta-Developer  assigned!

**Comment by Shinu-ster** [comment]
Hey i would love to work on this too. I want to make my first pr for hacktoberfest
can you assign me too

**Comment by Shinu-ster** [comment]
Or If possible can you create a new issue stating the problem Improving the UI of about us page and assign me under hacktober fest would love to work on that too

**Comment by vishalverma9572** [comment]
@TusharGupta-Developer , are you working on this issue?

**Comment by vishalverma9572** [comment]
@TusharGupta-Developer , I am removing you from this issue.

**Comment by vishalverma9572** [comment]
@Shinu-ster and others are welcome to work on this!

**Comment by Shinu-ster** [comment]
Assign me

**Comment by Fixito** [comment]
Hi! I'd would like to work on this issue. Can you assign it to me?

**Comment by vishalverma9572** [comment]
@Fixito & @Shinu-ster  assigned!

**Comment by Dcoder10M** [comment]
Hi @vishalverma9572 ,

I noticed that this issue was assigned to @Shinu-ster , but there hasn't been any activity for a while. I would love to help resolve this issue if it's still available. Could you please consider reassigning it to me?

Thank you!

**Comment by sankettank66** [comment]
Hey @vishalverma9572,
If no one is working on this issue, please assign it to me.

**Comment by vishalverma9572** [comment]
@Dcoder10M @sankettank66   
@Shinu-ster is already working on this issue, so feel free to focus on other tasks for now. 
If there's any difficulty or delay from his side, I'll inform you, and you can pick it up then.
