### ISSUE TITLE
Resolve the negative timing error while creating a quiz and fixing some UI issues

### ISSUE THREAD

**Issue by shreysachani** [vishalverma9572/QuizMaster#28]
![image](https://github.com/user-attachments/assets/4fce77b5-fa34-43dc-b40a-b66709dc011a)

In the above image while you create a quiz there is no validation for negative timings on quiz and also because of that when you take the quiz, it automatically ends because of negative timing being for the quiz.

Also

![image](https://github.com/user-attachments/assets/bd69a119-d9ff-4abf-9b05-5a0c636f2818)
![image](https://github.com/user-attachments/assets/5681c368-51a0-498d-b904-9de635d4cea7)

There are some UI issues in the input fields in profile section, create quiz section. They are not center aligned.

**Comment by vishalverma9572** [comment]
@shreysachani  assigned!
