### ISSUE TITLE
Implement proper input validation at backend

### ISSUE THREAD

**Issue by PorePranav** [vishalverma9572/QuizMaster#32]
The backend of this application currently lacks comprehensive input validation, which could lead to invalid or unsafe data being processed and stored in the database. To enhance the application's robustness, we need to implement input validation across various endpoints using libraries such as **Zod**

#### Tasks:
1. **Identify Inputs**: Review all API endpoints to identify inputs that require validation, including but not limited to user registration, login, and other APIs, etc.
2. **Implement Zod Validation**: 
    - Define Zod schemas for input validation, ensuring that all required fields are validated with appropriate data types, length constraints, and custom error messages.
    - Integrate these validation schemas into the backend service logic, rejecting requests with invalid data.
3. **Error Handling**: Ensure proper error handling by providing descriptive validation error responses to the client in case of invalid inputs.

#### Expected Outcome:
- Input validation is implemented across the backend using Zod.
- Invalid requests are rejected with meaningful error messages.
- The backend is more resilient to faulty or malicious inputs.

**Comment by vishalverma9572** [comment]
@PorePranav assigned! Since you are going to work in the Backend So be careful...
All the Best..

**Comment by Dcoder10M** [comment]
Hi @vishalverma9572 ,
I would love to help resolve this issue if it's still available. Please consider reassigning it to me.
Thank you!

**Comment by vishalverma9572** [comment]
@Dcoder10M, Thanks for the update! Since this issue is resolved, you can now focus on other open issues. Let me know if you need any assistance.
