### ISSUE TITLE
Adding a button to toggle between light and dark theme

### ISSUE THREAD

**Issue by TakangNina** [vishalverma9572/QuizMaster#33]

**Comment by vishalverma9572** [comment]
@TakangNina we don't have dark mode on our website at the moment. Thanks for your concern, though. You can work on other issues

**Comment by TakangNina** [comment]
Thank you

**Comment by TakangNina** [comment]
Can I work on including the dark theme though?

**Comment by vishalverma9572** [comment]
@TakangNina Sorry But this website is only designed for one theme mode. You cam contribute in other features or bugs

**Comment by TakangNina** [comment]
alright
