### ISSUE TITLE
Add old password field on the profile site

### ISSUE THREAD

**Issue by TommiNICE** [vishalverma9572/QuizMaster#37]
Hi Vishal,
I would like to add a field in the profile site. 
Usually when you want to change your password you have to enter your old password. 
This is what would like to add. I would like to work on this feature on both sites, frontend and backend.
Let me know if you agree to my proposal.
Best
Tommi
![image](https://github.com/user-attachments/assets/dfde1566-fca8-47b3-9423-f5ee19adb270)

**Comment by vishalverma9572** [comment]
@TommiNICE, go for it!

**Comment by TommiNICE** [comment]
Thank you, @vishalverma9572.
I have a problem with the app running locally. I cannot Sign Up. I think, it's because I miss something with the mongodb. Until now, I used mongodb cloud. Can you help me with that? Or someone else?
Then there is something else that I don't understand. The EMAIL_USER and EMAIL_PASSWORD for the Google API. There's nothing in the documentation.
