### ISSUE TITLE
ADD A QUIZ GAME PAGE

### ISSUE THREAD

**Issue by Swastik200** [vishalverma9572/QuizMaster#49]
WILL ASK QUESTIONS WITH OPTIONS AND AT END DISPLAY THE SCORE SIMPLE PROJECT USING HTML AND CSS

**Comment by vishalverma9572** [comment]
@Swastik200 , thanks for your concern, but our project is not related to that. Our platform is focused on providing a medium to take and manage  quizzes and viewing stats.

**Comment by vishalverma9572** [comment]
@Swastik200, You can work on other issues. if you are facing any issue while running this project locally or while working on it you can ask for help
