### ISSUE TITLE
Profile image upload while signup should added and render the image in the profile section for better UX.

### ISSUE THREAD

**Issue by VidyaSagarMehar** [vishalverma9572/QuizMaster#54]
- To improve the UX, it should also have a image upload functionality.
- conditional rendering of the upload button based on login/signup page.
- Add a edit image button on the profile page to allow changing the profile image.
- username: Actual username and email: Actual email can be replaced as ActualUsername and ActualEmail no need to describe since it is obvious.

**Comment by Prachirsh** [comment]
I would like to work on it. Can you assign it to me?

**Comment by vishalverma9572** [comment]
@VidyaSagarMehar I can't accept this issue because I have limited database space, and this feature would increase the database load. That's why I am not accepting this issue or the PR.

**Comment by vishalverma9572** [comment]
@VidyaSagarMehar Thank you for your contribution though. Please work on an accepted issue. Or create a issue and work only after a approval.
