### ISSUE TITLE
Update the button styling on the homepage 

### ISSUE THREAD

**Issue by vishalverma9572** [vishalverma9572/QuizMaster#56]
Add React Icons to enhance the visual appeal of the homepage, and ensure that the multiple buttons & icons are styled consistently with the updated buttons and are responsive across different screen sizes.

**Comment by Shinu-ster** [comment]
Can I work on this

**Comment by vishalverma9572** [comment]
@Shinu-ster why not!

**Comment by Dcoder10M** [comment]
Hi @vishalverma9572 ,
I would love to help resolve this issue if it's still available. Please consider reassigning it to me.
Thank you!

**Comment by MrSwapnilRahate** [comment]
I also interested with the same to show my creativity and knowledge. 
If you need any kind of help, please feel free to reach out me.

**Comment by saradha04** [comment]
i would like to solve this issue here. pleasured to do this.
