### ISSUE TITLE
Restyling the Take test section

### ISSUE THREAD

**Issue by ayush-848** [vishalverma9572/QuizMaster#6]
![image](https://github.com/user-attachments/assets/885e546d-f07f-4a57-8ab9-5633d4c62ac0)

**Comment by Aneeshaik** [comment]
Could you please tell me how to find the Quiz ID? I am unable to find it.

**Comment by ayush-848** [comment]
> Could you please tell me how to find the Quiz ID? I am unable to find it.

Idk 
Maybe it will be seen after you create a test

**Comment by Aneeshaik** [comment]
okay! Thank you for your response

**Comment by vishalverma9572** [comment]
@ayush-848 You can work on this.

**Comment by ayush-848** [comment]
> @ayush-848 You can work on this.

@vishalverma9572 is anyone working on the create test component??

**Comment by vishalverma9572** [comment]
issue  #10  looks similar but he is working on category wise selection of quiz...

**Comment by ayush-848** [comment]
> issue #10 looks similar but he is working on category wise selection of quiz...

![image](https://github.com/user-attachments/assets/4c9588ae-18f7-47d1-8ea4-a54429813011)
@vishalverma9572 check this

**Comment by ayush-848** [comment]
![image](https://github.com/user-attachments/assets/ee0e1358-f4a7-47dc-8194-9b574ac67c44)
@vishalverma9572 I was thinking of fixing this part. Should I make a new issue??

**Comment by vishalverma9572** [comment]
@ayush-848  can you attach image of quiz after fetching the quiz with given quiz id..

**Comment by ayush-848** [comment]
> @ayush-848 can you attach image of quiz after fetching the quiz with given quiz id..

It say not found

**Comment by ayush-848** [comment]
![image](https://github.com/user-attachments/assets/01233beb-3e9c-4a9d-ba07-d4c462bda79d)
@vishalverma9572 Backend shows ok but Quiz is showing not found

Should I do the PR

**Comment by vishalverma9572** [comment]
@ayush-848  Please resolve this issue first before creating the PR. You're likely facing this problem because you haven't parsed the response correctly.

**Comment by ayush-848** [comment]
> @ayush-848 Please resolve this issue first before creating the PR. You're likely facing this problem because you haven't parsed the response correctly.

![image](https://github.com/user-attachments/assets/b0eeeac5-b219-46b8-abb8-621d0c57d047)
I made a quiz and gave the id
It works

**Comment by vishalverma9572** [comment]
@ayush-848 , looks good! Create a PR after finalizing everything. You might consider adding the fetched test in a different div if possible.
