### ISSUE TITLE
Hide Sign In/Sign Up Buttons for Logged-In Users and Prevent Access to Login/Register Pages When Authenticated

### ISSUE THREAD

**Issue by Shinu-ster** [vishalverma9572/QuizMaster#60]
When a user is logged in, the home page currently still displays the Sign In and Sign Up buttons, and these buttons are functional even though the user is authenticated. Additionally, it allows users to access the login and register pages despite already being logged in, leading to an unnecessary login flow.

Following tasks are needed to be done to fix this:

- [ ] Update the logic on the home page to hide the Sign In/Sign Up buttons when the user is authenticated.

- [ ] Implement a route guard for login and register pages, which checks if the user is already authenticated and redirects them if a valid token is found.

I would like to fix this issue. Can assign me with hacktober label.

**Comment by oluwabukola2610** [comment]
I would like to fix this issue.

**Comment by vishalverma9572** [comment]
@Shinu-ster assigned!

**Comment by vishalverma9572** [comment]
@oluwabukola2610 , @Shinu-ster is working on that, so you can find another issue or create one of your choice.
