### ISSUE TITLE
Improvements in the Frontend UI Design in the TestPage.js and css files

### ISSUE THREAD

**Issue by Anirban780** [vishalverma9572/QuizMaster#66]
@vishalverma9572 while checking how the test taking system works, I have found that the UI design of the page where the test questions are loaded and user can select answer, basically in TestPage.js and css files, is lacking and can be improved.
Thus, could you assign this task to me ?
![Screenshot (438)](https://github.com/user-attachments/assets/a557a7d4-c0b8-4d81-9df2-c5fe5b120a5d)

**Comment by vishalverma9572** [comment]
@Anirban780 , This page is quite complex, and we need to render instructions on the same page with multiple checks to ensure the user can't bypass them, attempt, or modify the results. I suggest you thoroughly understand the code of this page before starting to work on it.

**Comment by vishalverma9572** [comment]
@Anirban780 , I'm assigning this to you. Before starting, please explain exactly what improvements you plan to make

**Comment by Anirban780** [comment]
@vishalverma9572  Ok, I will mostly work on the css file and if there are any minor changes to make in the js file, I will first let you know.

**Comment by vishalverma9572** [comment]
@Anirban780 , If the user's status is marked as "taken," display a message in place of the instructions that says, "You have already taken the test." This will be more interactive then blank screen.

**Comment by vishalverma9572** [comment]
@Anirban780 , any updates?

**Comment by Anirban780** [comment]
I'm still working on it, I'll update you by EOD

**Comment by vishalverma9572** [comment]
![image](https://github.com/user-attachments/assets/8f1466ee-f87b-4c98-b4b9-545abfefe53a)
Please update the background, as it currently doesn't look professional. Also, could you provide me with an update on the other parts? Thank you!
