### ISSUE TITLE
Enhancement + Feat: SignIn + SignUp pages

### ISSUE THREAD

**Issue by Sambit-Mondal** [vishalverma9572/QuizMaster#7]
### Enhancement: 
The SignIn and SignUp aren't centred properly, which leads to a bad User Experience. I want to fix them.

![Screenshot 2024-10-02 104727](https://github.com/user-attachments/assets/55085120-2cc7-466a-92a9-5d0bdfa198c0)

![Screenshot 2024-10-02 104746](https://github.com/user-attachments/assets/edfe3a4f-2ab1-4be8-8b16-15964abe5bc6)

### Feat:
I want to add Social Media login options (Google, Facebook) so as to make it easier for users to login.

Kindly assign me this issue under HacktoberFest 2024.

**Comment by vishalverma9572** [comment]
@Sambit-Mondal go for it! Thanks for your effort. Please make sure to test everything thoroughly to ensure it's working properly before creating the PR.

**Comment by Sambit-Mondal** [comment]
@vishalverma9572 Sure, I'll try my best!
