### ISSUE TITLE
User guide accessible only to authorized use 

### ISSUE THREAD

**Issue by vishalverma9572** [vishalverma9572/QuizMaster#70]
Currently, the User Guide page is restricted to authenticated users only. This should be accessible to all users, including non-authenticated ones, from the home page. Update the authentication logic to allow public access to the User Guide page and submit a new PR after resolving the issue.

**Comment by ifeelsam** [comment]
Can I try?

**Comment by vishalverma9572** [comment]
@ifeelsam , sure!

**Comment by ifeelsam** [comment]
#74 
i tried on deployed site as well, i can reach the "/user-guide" without auth

**Comment by Sanchitagarwal7** [comment]
@ifeelsam from home screen the upon clicking its somehow directing to "/userguide" (idk how its changed), whereas the proper path is "/user-guide" to direct to user guide, so changing that might solve the issue

**Comment by ifeelsam** [comment]
@Sanchitagarwal7 yea, i already changed it, see here #74 
i wasn't getting any options to link the PR here
