### ISSUE TITLE
[Feat] - Add PR templates

### ISSUE THREAD

**Issue by vishalverma9572** [vishalverma9572/QuizMaster#77]
I would like to create a Pull Request (PR) template for our GitHub repository to standardize the process of submitting PRs. This template will guide contributors in providing essential information about their changes, making it easier for reviewers to understand the context and purpose of each submission. 

The PR template will include sections for:

- **Title:** A clear and concise title summarizing the changes.
- **Description:** A detailed explanation of the changes made, including the problem being addressed and how the changes resolve it.
- **Related Issues:** Any associated issue numbers or links that this PR addresses.
- **Type of Change:** A checkbox list indicating the nature of the changes (e.g., bug fix, new feature, documentation, etc.).
- **Checklist:** A series of checkboxes for contributors to confirm that they have completed essential tasks, such as testing their changes and updating documentation.
- **Screenshots:** A space for visual aids to demonstrate the changes, especially for UI modifications.

Implementing this PR template will enhance our workflow, improve communication, and ensure consistency in our contributions.

**Comment by Chioma-Okeke** [comment]
What do you need to be done here? I'd love to help

**Comment by vishalverma9572** [comment]
@Chioma-Okeke  I have updated Issue description. And please let me know If you want to work on this

**Comment by Chioma-Okeke** [comment]
Okay
I would love to help with this.
I have a question. Is having a title necessary when each PR has a title box?

**Comment by vishalverma9572** [comment]
@Chioma-Okeke , No, we don't need to add a title box explicitly, as it is already included.

**Comment by vishalverma9572** [comment]
@Chioma-Okeke , assigned!
