### ISSUE TITLE
Improve Backend by making routes and controllers

### ISSUE THREAD

**Issue by Wasif0787** [vishalverma9572/QuizMaster#8]
I saw that route file contains all function , but the function should be in controllers file , I can improve the code in backend by diving it into different folders

**Comment by Wasif0787** [comment]
Okk I'll be careful while working

**Comment by Wasif0787** [comment]
why there are no package.json in the frontend

**Comment by Wasif0787** [comment]
Please close this issue as completed

**Comment by vishalverma9572** [comment]
done!
