### ISSUE TITLE
if user has invalid jwt token at any authorised page it should redirect to /login

### ISSUE THREAD

**Issue by vishalverma9572** [vishalverma9572/QuizMaster#80]
if user has invalid jwt token at any authorised page it should redirect to /login and clear the jwt token from local storage

**Comment by ajay0180** [comment]
can you assign this issue to me?

**Comment by Kheria1509** [comment]
can you assign this issue to me to resolve it?

**Comment by vishalverma9572** [comment]
@ajay0180 , assigned!

**Comment by vishalverma9572** [comment]
@Kheria1509 , you can work other issues!

**Comment by vishalverma9572** [comment]
@ajay0180 , any updates?

**Comment by ajay0180** [comment]
i will update you till tomorrow..

**Comment by ajay0180** [comment]
Actually , i am busy in my college sessional tests ,That is why I am out of this work , @vishalverma9572  I will complete this assigned issue till Sunday. Sorry for the delay..

**Comment by SatyamThakur0** [comment]
Since it have been more than two weeks to opened this issue and no PR raised for this issue so, i want to work on this.

**Comment by vishalverma9572** [comment]
@SatyamThakur0, Assigned!
