### ISSUE TITLE
Redirect unauthorized users to login/signup and return to attempted secure route upon authentication

### ISSUE THREAD

**Issue by vishalverma9572** [vishalverma9572/QuizMaster#88]
**Issue Description:**

Currently, there is a problem when an unauthorized user attempts to access a secure route. Here’s a breakdown of the issue and proposed solution:

- **Problem:**
  - When an unauthorized user tries to access a secure route:
    - They either encounter a blank screen or
    - They are redirected to the login page without any context of the original route.
  
- **Proposed Solution:**
  - If an unauthorized user tries to access a secure route:
    - They should be redirected to the login or signup page.
    - After successful authentication (login/signup):
      - The user should be redirected back to the originally intended secure route.
      - This can be done by passing the intended route through URL parameters 

- **Benefits:**
  - Improves user experience by making sure they don’t lose track of the page they were trying to access.
  - Ensures a smooth flow between authentication and accessing secure content.

**Comment by Vikas350** [comment]
Hi @vishalverma9572, I want to contribute to this, can you please assign this to me?

**Comment by Rahulagg13** [comment]
Hey, can you assign this issue to me?

**Comment by SatyamThakur0** [comment]
Hey, @vishalverma9572 , I also want you to assign this issue to me...

**Comment by vishalverma9572** [comment]
@Rahulagg13 @Vikas350 , this issue is almost resolved. so you guys can work on other issues!
