### ISSUE TITLE
[BUG] <description> search button whenever click no loading animation is display

### ISSUE THREAD

**Issue by Kheria1509** [vishalverma9572/QuizMaster#90]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

When the button is clicked, no loading animation is displayed, leading to a poor user experience. This lack of visual feedback leaves users uncertain whether their action was successfully processed or not. Adding a loading indicator would enhance usability by providing clear feedback during the action's execution.

### Steps to Reproduce

Include any relevant details like:

- What page you were on...
- What you were trying to do...
- What went wrong...

### Screenshots

![Screenshot 2024-10-08 012135](https://github.com/user-attachments/assets/7895d9f3-bbb8-4bcd-9b81-4281798dd29e)

https://github.com/user-attachments/assets/234a06e8-5fa6-44c0-bcf1-18b4ed5a8cdf

### Do you want to work on this issue?

Yes

**Comment by Kheria1509** [comment]
allow me to contribute in this issue.
@vishalverma9572

**Comment by vishalverma9572** [comment]
@Kheria1509 assigned! please do the same for login and logout

**Comment by Dcoder10M** [comment]
Hi @vishalverma9572 ,
I would love to help resolve this issue if it's still available. Please consider reassigning it to me.
Thank you!

**Comment by Milindddd** [comment]
@vishalverma9572  please close this issue as completed in pr #126

**Comment by Kheria1509** [comment]
@vishalverma9572  i think you should open this issue again as it has not be done for login and logout .
This time allow me to contribute in this issue .

**Comment by Kheria1509** [comment]
@vishalverma9572  add hacktoberfest also!!
