### ISSUE TITLE
[FEATURE] Add Logout Confirmation Prompt

### ISSUE THREAD

**Issue by Dcoder10M** [vishalverma9572/QuizMaster#95]
### Is this a unique feature?

- [x] I have checked "open" AND "closed" issues and this is not a duplicate

## Description
When a user clicks on the **Logout** button, the app currently logs the user out immediately without any confirmation. Instead, the app should display a confirmation prompt asking the user if they are sure they want to log out. This will prevent accidental logouts.

## Steps to reproduce
1. Log in to the app.
2. Click on the **Logout** button in the navigation bar.
3. Notice that the user is logged out instantly, without any confirmation.

## Expected behavior
After clicking the **Logout** button, the app should display a confirmation dialog (e.g., "Are you sure you want to log out?"). If the user confirms, they are logged out; otherwise, the logout process is canceled.

## Screen Recording
[Logout.webm](https://github.com/user-attachments/assets/78bcdcce-1257-4665-88f8-f8edb4dc8980)

## Proposed Solution
Add a confirmation dialog when the user clicks **Logout**. The dialog should ask, "Are you sure you want to log out?" with options to **Confirm** or **Cancel**.

### Do you want to work on this issue?

Yes

**Comment by Dcoder10M** [comment]
@vishalverma9572  Can you please assign this task to me under hactoberfest?

**Comment by vishalverma9572** [comment]
@Dcoder10M , I am assigning this task to you. Please ensure that you follow our current code structure and maintain consistency with the existing UI theme.
