### ISSUE TITLE
[BUG] Automatic Scrolling to Fetched Test Details Menu Not Triggering

### ISSUE THREAD

**Issue by Milindddd** [vishalverma9572/QuizMaster#97]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

When the test details are fetched, the page does not automatically scroll down to the "Test Details" section as expected. Users are required to manually scroll to view the fetched details, leading to a poor user experience. The issue is that the automatic scrolling function is either not triggered or not functioning correctly after the data is loaded.

### Steps to Reproduce

Include any relevant details like:

- go to take test page
- enter quiz ID
- click search
- the page remains as it is and we are not taken to the test details page
- there is no action on the page that reflects your input, hence creates confusion
- addition of a progress circle indication and automatic scroll can help improve the user experience 

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

1. Automatic Scroll Feature
To automatically scroll to a specific section (like the fetched test details), you can use JavaScript. Once the content is loaded or fetched, trigger a function that scrolls to the section where the test details are displayed. You can use the scrollIntoView() method in JavaScript, which smoothly scrolls the page to a specific element. For example, after the test details are fetched, the script will automatically scroll down to the section where they are located.

Steps:
Identify the section or element where the fetched content will be displayed (e.g., a div with an ID or class).
Use JavaScript to scroll to that section once the content is loaded. You can trigger the scroll when the fetch request is completed, or when the page loads, depending on your use case.
2. Loading Circle
To add a loading spinner (circle) while the content is being fetched:

First, create a visual element for the loading spinner using CSS. You can design a simple spinning circle that appears in the center of the screen while the data is being fetched.
Then, use JavaScript to show this spinner when the fetch process starts and hide it when the data has been successfully loaded.
This involves toggling the visibility of the spinner using JavaScript, making it visible at the start of the fetch request and hiding it once the fetch is complete and the content is displayed.
Steps:
Create the spinner as an HTML element styled with CSS to animate the loading effect.
Display the spinner before fetching the data.
Hide the spinner after the data is fetched and the content is loaded, then scroll down to the relevant section.

**Comment by vishalverma9572** [comment]
@Milindddd , assigned!

**Comment by vishalverma9572** [comment]
@Milindddd , follow the contribution guidelines while working!

**Comment by vishalverma9572** [comment]
@Milindddd , any updates?
