### ISSUE TITLE
real-time password strength analysis

### ISSUE THREAD

**Issue by yalsik86** [vishalverma9572/QuizMaster#98]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

better passwords ensuring better security for new users

### Proposed Solution

real-time password strength analysis feature for sign-up page

### Screenshots

![Screenshot 2024-10-11 030516](https://github.com/user-attachments/assets/b61c152d-ea02-4c70-ac28-b58646588216)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I will be adding a strength bar to indicate password strength. 
The bar will increase as the password includes uppercase letters, lowercase letters, numbers, and special characters.

**Comment by vishalverma9572** [comment]
@yalsik86 , assigned!
